version: "3.1"
services:
  dashboard:
    image: node:14.19.1
    network_mode: "service:shim"
    command:
      bash -c "npm rebuild node-sass && npm run serve"
    working_dir:
      /dashboard
    volumes:
      - ./:/dashboard:cached
    environment:
      - APIROOT=http://localhost:8080/api
      - FORMS_URL=http://localhost:8081
      - OVERVIEW_URL=/
      - SEND_USER_TO_MEDITOR=/meditor
      - DAAC_NAME=local
      - STAGE=LOCALHOST-Development
      - SHOW_DISTRIBUTION_API_METRICS=false
      - AUTH_METHOD=earthdata
      - REQUEST_HIDE_BUTTON_VERBAGE=Withdraw
      - REQUEST_UNHIDE_BUTTON_VERBAGE=Restore
  shim:   # empty container to open ports
    image: node:14.19.1
    command:
      bash -c "tail -f /dev/null"
    working_dir:
      /dashboard
    volumes:
      - ./:/dashboard:cached
    ports:
      - "3000:3000"
