AccessTokensTable:
  read: 5
  write: 1
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: accessToken
      type: S
      schema: HASH

CollectionsTable:
  read: 5
  write: 1
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: name
      type: S
      schema: HASH
    - name: version
      type: S
      schema: RANGE

ProvidersTable:
  read: 5
  write: 1
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: id
      type: S
      schema: HASH

RulesTable:
  read: 5
  write: 1
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: name
      type: S
      schema: HASH

UsersTable:
  read: 5
  write: 1
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: userName
      type: S
      schema: HASH

GranulesTable:
  read: 5
  write: 10
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: granuleId
      type: S
      schema: HASH
    - name: collectionId
      type: S
  # overrides the default behavior of adding all defined attributes to KeySchema
  KeySchema:
    - KeyType: HASH
      AttributeName: granuleId
  GlobalSecondaryIndexes:
    - IndexName: collectionId-granuleId-index
      KeySchema:
      - KeyType: HASH
        AttributeName: collectionId
      - KeyType: RANGE
        AttributeName: granuleId
      Projection:
        ProjectionType: ALL

PdrsTable:
  read: 5
  write: 2
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: pdrName
      type: S
      schema: HASH


ExecutionsTable:
  read: 5
  write: 10
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: arn
      type: S
      schema: HASH

FilesTable:
  read: 5
  write: 10
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: bucket
      type: S
      schema: HASH
    - name: key
      type: S
      schema: RANGE

AsyncOperationsTable:
  read: 5
  write: 10
  pointInTime: '{{enablePointInTime}}'
  attributes:
    - name: id
      type: S
      schema: HASH

SemaphoresTable:
  read: 5
  write: 10
  pointInTime: false
  attributes:
    - name: key
      type: S
      schema: HASH
